### ISSUE TITLE
Readme 404 - Hugo Documentation?

### ISSUE THREAD

**Issue by Luunae** [simulogics/prosperousuniverse-docs#73]
This line in the readme:

> We are using a Hugo theme with lots of features. Please have a look at their [documentation](https://learn.netlify.com/en/cont/) for more information about it.

The link goes to a Netlify 404? I think? I'm not even sure what the link is supposed to be, so I can't do a pull request for it.

**Comment by molp** [comment]
The link should go to the [hugo theme relearn](https://themes.gohugo.io/themes/hugo-theme-relearn/). I'll fix that. Thanks for noticing!

**Comment by molp** [comment]
Fixed
